jobs:
  main:
    image: yoshwata/centos:1.0
    requires: [~pr, ~commit]
    environment:
      SD_HAB_ENABLED: "false"
    steps:
      - echo: echo $SD_GIT_WRAPPER
      - git: $SD_GIT_WRAPPER "git version"
